"""Paired single-vs-multi comparison on one read-heavy comprehension task.

The task is "understand this codebase and write the answer down" over a corpus
that no single context window can hold. Unlike the writable comparison there are
no child Patches to read and integrate, so the main agent's cost is synthesis
only - which is the arm of the trade-off record 074 could not separate.

This uses the repository's own `execution_strategy` comparison: two arms of the
same benchmark, baseline `single` and candidate `multi`, run by `traceh eval`
with one run plan. Nothing here scores anything; the original comparison owner
decides the verdict from the two reports.
"""

import argparse
import asyncio
import json
import shutil
import subprocess
from pathlib import Path
from tempfile import TemporaryDirectory

from evaluation_fixtures import capture_fixture_tree, fixture_tree_limits

from live_dynamic_collaboration.comprehension_materials import (
    ADR_COUNT,
    DELIVERABLE,
    EXCLUDED_PACKAGES,
    MIN_ANCHORED,
    MIN_CITED_FILES,
    MIN_CITED_PACKAGES,
    PUBLIC_REQUIREMENT,
    REQUIREMENT,
    SECTIONS,
    checks,
    corpus_paths,
    tree_digest,
)
from live_dynamic_collaboration.materials import budgets, write
from traceh.evaluation.inputs import digest_bytes, read_input
from traceh.evaluation.repositories import initial_tree_digest
from traceh.sandbox.config import load_sandbox_file

CASE = "comprehension-large-codebase"
AUTHORIZED = 6
MODEL = "deepseek-v4.1-flash"
REPETITIONS = 1
EVAL_TIMEOUT_SECONDS = 21_600

# Reading is bounded by steps and tool calls long before tokens: read_file pages
# at 120 lines, so these are the dimensions that decide how much of the corpus an
# agent can actually see. Both arms share one profile, so the ceilings below must
# fit the more demanding arm; the ledger carves every assistant's allowance out
# of the main's, which is what keeps the two arms comparable.
#
# These are deliberately over-provisioned, and steps are held equal to tool calls
# so neither dimension binds before the other. Paging the entire corpus would
# take 693 read_file pages, which no selective reading strategy approaches; the
# allowance here is several times any plausible one, so an arm that fails to
# cover the corpus is limited by the model's own context - the thing under
# observation - and not by this fixture.
ASSISTANT_TOKENS = 5_000_000
ASSISTANT_TOOL_CALLS = 400
ASSISTANT_STEPS = ASSISTANT_TOOL_CALLS
ASSISTANT_WALL_MS = 2_700_000
MAIN_TOKENS = 16_000_000
MAIN_TOOL_CALLS = 600
MAIN_STEPS = MAIN_TOOL_CALLS
MAIN_TURN_WALL_MS = 7_200_000
# Round 6's multi arm hit exactly 8192 output tokens while emitting a ~20,000
# character document in one call, and the truncated tool-call JSON ended the
# run. The deliverable's own bound is 24,000 characters, so one reply has to
# be able to carry it.
OUTPUT_TOKENS = 32_768
RETAINED_TOKENS = 500_000
MAX_REPORT_CHARS = 24_000
CODER_TOKENS = MAIN_TOKENS + AUTHORIZED * ASSISTANT_TOKENS
CODER_STEPS = MAIN_STEPS + AUTHORIZED * ASSISTANT_STEPS
CODER_TOOL_CALLS = MAIN_TOOL_CALLS + AUTHORIZED * ASSISTANT_TOOL_CALLS
CODER_WALL_MS = MAIN_TURN_WALL_MS + AUTHORIZED * ASSISTANT_WALL_MS


def _environment(env_file):
    """Read the authorized non-secret endpoint from the explicit env file."""
    values = {}
    for line in env_file.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, value = line.split("=", 1)
            values[key.strip()] = value.strip()
    base_url = values.get("TRACEH_BASE_URL")
    if not base_url:
        raise ValueError("comprehension-base-url-missing")
    return values, base_url


def _reference(initial: Path, paths: tuple[str, ...]) -> str:
    """A mechanically generated deliverable that satisfies the fixed check.

    It proves the check is satisfiable and that its failure mode is the missing
    or unfounded deliverable - not that the check measures explanation quality,
    which it deliberately does not.
    """

    code = [p for p in paths if p.startswith("src/traceh/") and p.count("/") > 2]
    by_package: dict[str, list[str]] = {}
    for name in code:
        by_package.setdefault(name.split("/")[2], []).append(name)
    chosen: list[str] = []
    for package in sorted(by_package):
        chosen.extend(sorted(by_package[package])[:2])
    anchored = []
    for name in chosen:
        for line in (initial / name).read_text(encoding="utf-8", errors="replace").splitlines():
            if line.startswith("def ") or line.startswith("class "):
                symbol = line.split("(")[0].split(":")[0].split()[1]
                anchored.append(f"`{name}:{symbol}`")
                break
        else:
            anchored.append(f"`{name}:1`")
    body = [
        SECTIONS[0],
        "A reference deliverable generated by the preflight, not an explanation.",
        SECTIONS[1],
        *(f"- {item}" for item in anchored),
        SECTIONS[2],
        "Reference text only.",
        SECTIONS[3],
        "Reference text only.",
        SECTIONS[4],
        "Everything: this file is generated, not read.",
    ]
    text = "\n\n".join(body) + "\n"
    filler = "\nThis paragraph pads the reference deliverable to the required length.\n"
    while len(text) < 4_200:
        text += filler
    return text


def prepare(repository: Path, sandbox: Path, output: Path, env_file: Path) -> None:
    values, base_url = _environment(env_file)
    output.mkdir(parents=True, exist_ok=False)
    (output / "sandbox.json").write_bytes(sandbox.read_bytes())
    policy = load_sandbox_file(output / "sandbox.json").policy
    paths = corpus_paths(repository)
    initial = output / "material" / "initial"
    initial.mkdir(parents=True)
    contents: dict[str, bytes] = {}
    for relative in paths:
        target = initial / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        data = (repository / relative).read_bytes()
        target.write_bytes(data)
        contents[relative] = data
    # Keep the materialized tree byte-identical on any platform.
    for name, text in ((".gitattributes", "* -text\n"), (".gitignore", "__pycache__/\n")):
        (initial / name).write_bytes(text.encode("utf-8"))
        contents[name] = text.encode("utf-8")
    paths = tuple(sorted(contents))
    if len(paths) > 256 or sum(len(v) for v in contents.values()) > 8 * 1024 * 1024:
        raise ValueError("comprehension-corpus-over-frozen-bound")
    if policy.limits.workspace_files < len(paths) + 8:
        raise ValueError("comprehension-sandbox-workspace-files-too-small")
    digest = tree_digest(contents)
    verifier = checks(digest)
    if len(verifier) > 4096:
        raise ValueError("comprehension-verifier-argument-too-long")
    verification = {
        "plan_id": CASE,
        "plan_version": 1,
        "protocol_version": 3,
        "commands": [
            {
                "public_requirement": PUBLIC_REQUIREMENT,
                "command_id": "citation-contract",
                "argv": ["python", "-B", "-c", verifier],
                "timeout_ms": 60_000,
            }
        ],
        "environment": {
            "policy_id": "comprehension-no-dependencies",
            "passthrough": [],
            "overrides": {"PYTHONDONTWRITEBYTECODE": "1", "PYTHONIOENCODING": "utf-8"},
        },
        "max_output_bytes": 1048576,
    }
    write(
        output / "material/dataset.json",
        {
            "format": 3,
            "cases": [
                {
                    "case_id": CASE,
                    "group_id": CASE,
                    "requirement": REQUIREMENT,
                    "initial_tree": "initial",
            "initial_tree_limits": fixture_tree_limits(),
                    "sha256": initial_tree_digest(capture_fixture_tree(initial)),
                    "verification": verification,
                }
            ],
        },
    )
    settings = json.loads(
        (
            repository / "benchmarks/dynamic_collaboration_v1/development/benchmark.json"
        ).read_text(encoding="utf-8")
    )["task_settings"]
    settings.update(
        profile_id="comprehension-paired",
        default_mode="single",
        modes=["single", "multi"],
        retained_tokens=RETAINED_TOKENS,
        investigator_initial_tokens=ASSISTANT_TOKENS,
        max_report_chars=MAX_REPORT_CHARS,
    )
    # Readonly assistants only: this task has no child Patch to integrate, so the
    # main agent's cost is synthesis and nothing else.
    settings["roles"]["patch_author"] = None
    settings["task_budget"] = budgets(
        CODER_TOKENS + 200_000,
        CODER_STEPS + 40,
        CODER_TOOL_CALLS + 40,
        CODER_WALL_MS + 600_000,
        AUTHORIZED,
        2,
        1 + AUTHORIZED,
    )
    settings["roles"]["coder"].update(
        max_output_tokens=OUTPUT_TOKENS,
        max_turn_wall_milliseconds=MAIN_TURN_WALL_MS,
        budget=budgets(
            CODER_TOKENS, CODER_STEPS, CODER_TOOL_CALLS, CODER_WALL_MS, AUTHORIZED, 1, AUTHORIZED
        ),
    )
    settings["roles"]["investigator"].update(
        max_output_tokens=OUTPUT_TOKENS,
        max_turn_wall_milliseconds=ASSISTANT_WALL_MS,
        budget=budgets(
            ASSISTANT_TOKENS, ASSISTANT_STEPS, ASSISTANT_TOOL_CALLS, ASSISTANT_WALL_MS, 0, 0, 0
        ),
    )
    write(
        output / "material/benchmark.json",
        {
            "protocol_version": 3,
            "benchmark_id": "comprehension-paired-v1",
            "task_type": "product_task",
            "task_settings": settings,
            "dataset": {
                "file": "dataset.json",
                "sha256": digest_bytes((output / "material/dataset.json").read_bytes()),
            },
            "assessment": {
                "scorer_id": "product-durable-v1",
                "version": 1,
                "requires_review": False,
                "rubric": None,
            },
        },
    )
    write(
        output / "material/run-plan.json",
        {
            "format": 1,
            "benchmark_digest": digest_bytes((output / "material/benchmark.json").read_bytes()),
            "variants": [
                {"variant_id": "single-arm", "role": "baseline", "source": "current"},
                {"variant_id": "multi-arm", "role": "candidate", "source": "current"},
            ],
            "model": {
                "provider": values.get("TRACEH_PROVIDER", "openai-compatible"),
                "model": MODEL,
                "base_url": base_url,
                "api_key_env": values.get("TRACEH_API_KEY_ENV", "DASHSCOPE_API_KEY"),
                "script": None,
                # Six assistants and the main share one endpoint. A refused
                # request returns no completion, so retrying costs no tokens and
                # keeps a long run from dying on a transient limit. Both arms
                # get the identical policy.
                #
                # max_elapsed_seconds must exceed the provider's 120s HTTP
                # timeout (frozen below as model.timeout_seconds since ADR-0086):
                # retry.py refuses when elapsed >= max_elapsed_seconds, so the
                # round-2 value of 120 made a 120.27s timeout unretryable by
                # construction - the exact failure the policy existed to cover.
                "retry_policy": {
                    "max_attempts": 3,
                    "max_elapsed_seconds": 600,
                    "base_delay_seconds": 2,
                    "max_delay_seconds": 20,
                    "retry_after_cap_seconds": 60,
                    "jitter_ratio": 0.2,
                },
                "timeout_seconds": 120,
            },
            "execution": {
                "sandbox_config": "../sandbox.json",
                "max_trials": 2 * REPETITIONS,
                "timeout_seconds": EVAL_TIMEOUT_SECONDS,
                "shutdown_seconds": 60,
                "network_mode": "direct",
                "first_arm": "baseline",
            },
            "trials": {"repetitions": REPETITIONS},
            "comparison": {
                "format": 3,
                "kind": "execution_strategy",
                "requested_modes": ["single", "multi"],
                "min_pass_gain": None,
                "max_token_ratio": None,
                "max_tool_call_delta": None,
            },
        },
    )
    (output / "comparison_driver.py").write_bytes(Path(__file__).read_bytes())
    contract_path = output / "contract.json"
    write(
        contract_path,
        {
            "format": 1,
            "kind": "comprehension-paired-comparison",
            "case_id": CASE,
            "arms": ["single", "multi"],
            "repetitions": REPETITIONS,
            "model": MODEL,
            "env_file": str(env_file),
            "connection_digest": digest_bytes(base_url.encode("utf-8")),
            "corpus": {
                "files": len(paths),
                "bytes": sum(len(v) for v in contents.values()),
                "lines": sum(v.decode("utf-8", "replace").count("\n") for v in contents.values()),
                "excluded_packages": list(EXCLUDED_PACKAGES),
                "adr_count": ADR_COUNT,
                "tree_digest": digest,
                "contains_project_summary": False,
            },
            "round": 10,
            "round_change": (
                "Ceilings for the assistants, and the reply ceiling. Round 9 was the first round "
                "where the multi arm cleared the collaboration-plan gate: it submitted a plan "
                "after two self-corrected refusals, created six assistants and collected 18 "
                "reports. It then ran out because two assistants charged exactly their 1,500,000 "
                "token limit, while the main agent used only 15% of its own; per-assistant tokens "
                "therefore go to 5,000,000 and per-assistant tool calls to 400. The single arm "
                "failed that round on a truncated tool call at 16,384 output tokens, so the reply "
                "ceiling goes to 32,768, which this endpoint accepts. Repeated-call analysis "
                "showed 100 of 106 repeated signatures were different assistants each doing their "
                "own setup rather than one agent re-reading, so no scope change was made. Corpus, "
                "requirement, checks, roles, model and main-agent ceilings are unchanged."
            ),
            "prior_round": (
                "Rounds 1 and 2 were void, both from fixture settings rather than the mechanism "
                "under test. Round 1: a 60,000-character deliverable bound against an 8192-token "
                "reply truncated the tool-call JSON. Round 2: the bound was cut to 12,000, the "
                "model wrote 16,202 characters in one successful 5,826-token generation, detected "
                "the violation itself and was truncated while rewriting; its document otherwise "
                "passed every check offline (63 files, 16 packages, 83 anchors, no unresolvable "
                "citation). The round-2 multi arm died on the provider's fixed 120s HTTP timeout, "
                "unretryable because max_elapsed_seconds was also 120. Generation held ~110 "
                "tokens/second at 90k input, so there is no context-size degradation. This round "
                "changes only the deliverable bound and the retry elapsed budget; corpus, "
                "requirement, checks, roles and every ceiling are unchanged."
            ),
            "assistant_count_named_in_requirement": False,
            "authorized_assistants": AUTHORIZED,
            "assistant_role": "investigator",
            "patch_author_configured": False,
            "thresholds": {
                "min_cited_files": MIN_CITED_FILES,
                "min_cited_packages": MIN_CITED_PACKAGES,
                "min_anchored": MIN_ANCHORED,
            },
            "budgets": {
                "assistant_tokens_each": ASSISTANT_TOKENS,
                "assistant_steps_each": ASSISTANT_STEPS,
                "assistant_tool_calls_each": ASSISTANT_TOOL_CALLS,
                "coder_tokens": CODER_TOKENS,
                "coder_steps": CODER_STEPS,
                "coder_tool_calls": CODER_TOOL_CALLS,
                "retained_main_tokens": RETAINED_TOKENS,
                "pages_to_read_whole_corpus": sum(
                    -(-(value.decode("utf-8", "replace").count("\n") + 1) // 120)
                    for value in contents.values()
                ),
                "over_provisioned": (
                    "Steps equal tool calls so neither binds first, and the allowance is several "
                    "times any plausible selective-reading strategy. Paging every line of the "
                    "corpus is not a strategy either arm can afford in wall clock, so this "
                    "records the fixture's headroom, not a claim that an arm could read it all."
                ),
            },
            "eval_timeout_seconds": EVAL_TIMEOUT_SECONDS,
            "expected_handoff": (
                "Assistants are authorized more wall clock than one plan call may hold, so an "
                "await_report plan is refused before dispatch and the model must use "
                "dispatch_and_continue (ADR-0079). That is a stated consequence of the sizing, "
                "not a hidden instruction."
            ),
            "interpretation": (
                "Both arms run the same frozen corpus, requirement, checks, image and ceilings; "
                "only the requested execution strategy differs. The fixed check verifies "
                "citations mechanically and does not judge explanation quality. One replicate "
                "per arm is an observation, not a statistic, and the original comparison owner "
                "decides the verdict."
            ),
            "files": {
                p.relative_to(output).as_posix(): digest_bytes(p.read_bytes())
                for p in output.rglob("*")
                if p.is_file() and p != contract_path
            },
        },
    )


def validate(output: Path) -> dict:
    data = read_input(output, "contract.json").data
    if (output / "comparison_driver.py").read_bytes() != Path(__file__).read_bytes():
        raise ValueError("comprehension-driver-drift")
    for relative, digest in data["files"].items():
        if digest_bytes((output / relative).read_bytes()) != digest:
            raise ValueError("comprehension-material-drift")
    return data


def preflight(output: Path) -> None:
    validate(output)
    sandbox = load_sandbox_file(output / "sandbox.json")
    if sandbox.policy.network != "none" or sandbox.plugin_grants:
        raise ValueError("comprehension-sandbox-policy-unexpected")
    case = read_input(output / "material", "dataset.json").data["cases"][0]
    paths = corpus_paths_from(output)
    reference = _reference(output / "material/initial", paths)
    outcomes = []
    # "invented" is the rule that carries the weight: a deliverable that meets
    # every count but cites one path that is not in the tree must still fail.
    for shape in ("absent", "reference", "invented"):
        with TemporaryDirectory(prefix="traceh-comprehension-") as directory:
            work = Path(directory).resolve()
            shutil.copytree(output / "material/initial", work, dirs_exist_ok=True)
            repaired = shape == "reference"
            if shape == "reference":
                (work / DELIVERABLE).write_text(reference, encoding="utf-8")
            elif shape == "invented":
                (work / DELIVERABLE).write_text(
                    reference + "\nSee also `src/traceh/does_not_exist/router.py`.\n",
                    encoding="utf-8",
                )
            result = subprocess.run(
                [
                    "docker",
                    "--context",
                    sandbox.policy.docker_context,
                    "run",
                    "--rm",
                    "--pull",
                    "never",
                    "--network",
                    "none",
                    "--memory",
                    "256m",
                    "--pids-limit",
                    "64",
                    "--cpus",
                    "1",
                    "--mount",
                    f"type=bind,source={work},target=/work,readonly",
                    "--workdir",
                    "/work",
                    sandbox.policy.image,
                    *case["verification"]["commands"][0]["argv"],
                ],
                capture_output=True,
                text=True,
                encoding="utf-8",
                timeout=180,
            )
            expected = 0 if repaired else 1
            if result.returncode != expected or (
                not repaired and "AssertionError" not in result.stderr
            ):
                raise ValueError(
                    f"comprehension-preflight-failed:{shape}:{result.returncode}:"
                    f"{result.stderr[-400:]}"
                )
            if shape == "invented" and "citations that do not resolve" not in result.stderr:
                raise ValueError("comprehension-preflight-invented-wrong-reason")
            outcomes.append(
                {
                    "shape": shape,
                    "exit_code": result.returncode,
                    "stdout": result.stdout.strip()[-200:],
                    "reason": result.stderr.strip().splitlines()[-1][-160:]
                    if result.returncode
                    else "",
                }
            )
    write(
        output / "preflight.json",
        {
            "contract_digest": digest_bytes((output / "contract.json").read_bytes()),
            "outcomes": outcomes,
        },
    )


def corpus_paths_from(output: Path) -> tuple[str, ...]:
    """The frozen corpus as materialized, read back from the initial tree."""
    initial = output / "material/initial"
    return tuple(
        sorted(
            p.relative_to(initial).as_posix()
            for p in initial.rglob("*")
            if p.is_file() and not {".git", "__pycache__"} & set(p.parts)
        )
    )


async def run(output: Path, env_file: Path) -> int:
    from traceh.cli.main import _configure_from_environment, _eval, build_parser

    validate(output)
    preflight_data = read_input(output, "preflight.json").data
    if preflight_data["contract_digest"] != digest_bytes((output / "contract.json").read_bytes()):
        raise ValueError("comprehension-preflight-drift")
    with (output / "started.json").open("x", encoding="utf-8") as stream:
        stream.write('{"started":true}\n')
    args = build_parser().parse_args(
        [
            "eval",
            str(output / "material"),
            "--run-plan",
            str(output / "material/run-plan.json"),
            "--output",
            str(output / "experiment"),
            "--env-file",
            str(env_file),
        ]
    )
    _configure_from_environment(args)
    code = await _eval(args)
    write(output / "execution.json", {"exit_code": code})
    print(json.dumps({"exit_code": code}))
    return code


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("prepare", "preflight", "run"))
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--repository", type=Path)
    parser.add_argument("--sandbox", type=Path)
    parser.add_argument("--env-file", type=Path, default=Path(".env"))
    args = parser.parse_args()
    target = args.output.resolve()
    if args.action == "prepare":
        prepare(
            args.repository.resolve(),
            args.sandbox.resolve(),
            target,
            args.env_file.resolve(),
        )
    elif args.action == "preflight":
        preflight(target)
    else:
        raise SystemExit(asyncio.run(run(target, args.env_file.resolve())))
